Add new testdriver for OCF resource agent pgrepmgr.

diff --git a/ocf/credativ/pgrepmgr_test b/ocf/credativ/pgrepmgr_test
--- a/ocf/credativ/pgrepmgr_test
+++ b/ocf/credativ/pgrepmgr_test
@@ -43,7 +43,11 @@ PSQLCMD="/usr/bin/psql -v ON_ERROR_STOP=1 -qXtnAc"
 ## Internal status codes
 ##
 PGREPMGR_STATUS_IS_PRIMARY=0
-PGREPMGR_STATUS_IS_HOTSTANDBY=1
+PGREPMGR_STATUS_IS_HOT_STANDBY=1
+PGREPMGR_STATUS_IS_NOT_RUNNING=2
+PGREPMGR_STATUS_IS_FATAL=3
+PGREPMGR_STATUS_IS_BAD_CONN=4
+PGREPMGR_STATUS_IS_SCRIPT_ERR=5
 
 usage() {
 
@@ -258,11 +262,25 @@ pgrepmgr_status() {
 ##
 pgrepmgr_get_replication_status() {
 
-    if [[ $(runasowner "$PSQLCMD 'SELECT pg_is_in_recovery();'") = 'f' ]]; then
-	return $PGREPMGR_STATUS_IS_HOT_STANDBY
+    STATUS=$(runasowner "$PSQLCMD 'SELECT pg_is_in_recovery();'")
+
+    ## if psql didn't succeed, we need to check wether the instance is
+    ## actually running..
+
+    case $? in
+
+	1) ocf_log info "psql fatal"; return $PGREPMGR_STATUS_IS_FATAL;;
+	2) ocf_log info "psql bad conn"; return $PGREPMGR_STATUS_IS_BAD_CONN;;
+	3) ocf_log info "psql script err"; return $PGREPMGR_STATUS_IS_SCRIPT_ERR;;
+	*) ## fall through
+
+    esac
+
+    if [[ "$STATUS" = 'f' ]]; then
+	return $PGREPMGR_STATUS_IS_PRIMARY
     fi
 
-    return $PGREPMGR_STATUS_IS_PRIMARY
+    return $PGREPMGR_STATUS_IS_HOT_STANDBY
 
 }
 
@@ -270,11 +288,20 @@ pgrepmgr_get_replication_status() {
 ## PostgreSQL instance, make sure it is running
 pgrepmgr_monitor() {
 
-    ## We need to be careful with monitor probes against this resource
+    ## We need to be careful with monitor probes against this resource.
+    ## If this is an OCF probe, we simplify this test by just checking
+    ## wether a PostgreSQL instance is running, but only when no CLONE_LOCK
+    ## has been found.
 
-    if ! ocf_is_probe; then
+    if ocf_is_probe; then
 
-	ocf_log info "$RESOURCE monitor: no OCF probe"
+	## check wether any action is in progress
+	ocf_log info "OCF probe"
+
+	## CLONE_LOCK exists? If true, exit.
+	if [[ -f ${CLONE_LOCK} ]]; then
+	    return $OCF_SUCCESS
+	fi
 
 	if ! pgrepmgr_status; then
 	    ocf_log warn "$RESOURCE monitor: PostgreSQL not running"
@@ -283,10 +310,9 @@ pgrepmgr_monitor() {
 	fi
 
     else
-
-	## check wether any action is in progress
-	ocf_log info "OCF probe"
 	
+	ocf_log info "$RESOURCE monitor: no OCF probe"
+
 	## While this RA is running it might occur that syncing during
 	## a demote phase could have a very long duration. Check for a
 	## in-progress clone phase.
@@ -353,7 +379,7 @@ pgrepmgr_promote() {
 	    ## node is a standby and we want to promote it to a primary.
 	    ## Call repmgr to activate it.
 	    ocf_log info "Standby about to activated as primary node"
-	    runasowner ${OCF_RESKEY_repmgrbin}/repmgr -f ${OCF_RESKEY_repmgr_config} standby promote
+	    runasowner ${OCF_RESKEY_repmgrbindir}/repmgr -f ${OCF_RESKEY_repmgr_config} standby promote
 	    RC=$?
 
 	    if [[ $RC -ne 0 ]]; then
@@ -374,7 +400,157 @@ pgrepmgr_promote() {
 }
 
 pgrepmgr_demote() {
-    return $OCF_SUCCESS
+
+    ## Check wether this node is a primary instance
+    if pgrepmgr_get_replication_status -eq $PGREPMGR_STATUS_HOT_STANDBY ; then
+
+	ocf_log info "Instance is a standby already"
+	pgrepmgr_cib_status "START:instance is standby"
+	return $OCF_SUCCESS
+
+    else
+
+	## OK, now comes the tricky part. This is a primary instance, and we want to
+	## demote it to a standby. This requires us to build the standby from scratch.
+	## Since this could be a long operation, we need to take care.
+	if ! touch "$CLONE_LOCK" ; then
+	    ocf_log err "Could not create file \"${CLONE_LOCK}\""
+	    return $OCF_ERR_GENERIC
+	fi
+
+	## First, shut the server down, if not already done
+	if pgrepmgr_status ; then
+
+	    ocf_log debug "Shutting down PRIMARY"
+	    runasowner $OCF_RESKEY_pgctl -D $OCF_RESKEY_pgdata -m fast stop
+
+	    ## still alive?
+	    if pgrepmgr_status ; then
+
+		ocf_log debug "Shutting PRIMARY not succeeded, retry with immediate shutdown"
+
+		## oops, something is weird, maybe instance hangs somewhere,
+		## try to make it the hard way...
+		runasowner $OCF_RESKEY_pgctl -D $OCF_RESKEY_pgdata -m immediate stop
+
+		## Wait
+		count=0
+		while [ $count -lt $OCF_RESKEY_stop_escalate ]
+		do
+
+		    if ! pgrepmgr_status; then
+			# success
+			break;
+		    fi
+		    count = $(expr $count + 1)
+		    sleep 1
+
+		done
+
+	    fi
+
+	    if pgrepmgr_status ; then
+		## hmm okay, something really weird is going on,
+		## exit immediately
+		ocf_log err "An fatal error occured: instance is not shutting down"
+		pgrepmgr_cib_status "ERROR:instance not shutting down"
+		rm -f $CLONE_LOCK
+		return $OCF_ERR_GENERIC
+	    else
+		ocf_log "Shutdown immediate succeeded"
+	    fi
+
+	fi
+
+	## If reached here, PGSQL shut be successfully shut down, proceed:
+	## First, we need to make sure the old PGDATA isn't present anymore
+	ocf_log info "Dropping $OCF_RESKEY_pgdata"
+
+	## if ${OCF_RESKEY_pgdata} doesn't exist yet, nothing to do here.
+	## Otherwise we need to get rid of it, because we are forced
+	## to resync with the primary node. This is a very destructive
+	## task to do, so do some preliminary checks before.
+	if [[ -d "${OCF_RESKEY_pgdata}" ]]; then
+
+	    ## TODO: Much more checks here...
+
+	    if ! rm -rf "${OCF_RESKEY_pgdata}"; then
+		ocf_log err "Could not delete cluster directory \"${OCF_RESKEY_pgdata}\""
+		rm -f $CLONE_LOCK
+		return $OCF_ERR_GENERIC
+	    fi
+
+	fi
+
+	local FIN_RC=$OCF_ERR_GENERIC
+
+        ## Clone the current master
+	${OCF_RESKEY_repmgrbindir}/repmgr \
+	    -U${OCF_RESKEY_primary_user} \
+	    -d${OCF_RESKEY_primary_db} \
+	    -p${OCF_RESKEY_primary_port} \
+	    -D${OCF_RESKEY_pgdata} \
+	    standby clone ${OCF_RESKEY_primary_host}
+
+	RC=$?
+
+	## Handle error cases of repmgr and issue specific
+	## error messages
+
+	if [[ $RC -ne 0 ]]; then
+
+	    case $RC in
+		1) 
+		    ocf_log err "$RESOURCE demote: bad repmgr config"
+		    ;;
+		2)
+		    ocf_log err "$RESOURCE demote: rsync error"
+		    ;;
+		3)
+		    ocf_log err "$RESOURCE demote: pg_stop_backup() failed"
+		    ;;
+		5)
+		    ocf_log err "$RESOURCE demote: needs xlog"
+		    ;;
+		*)
+		    ocf_log err "$RESOURCE demote: failed to clone standby"
+		    ;;
+	    esac
+
+	    pgrepmgr_cib_status "ERROR:standby demote failed"
+
+	    ## an error has occured, cleanup
+	    rm -f $CLONE_LOCK
+	    return $OCF_ERR_GENERIC
+
+	else
+
+	    ocf_log info "STANDBY CLONE ok"
+	    ocf_log debug "Starting new standby"
+
+	    ## Now start the new standby
+	    runasowner ${OCF_RESKEY_pgctl} -D ${OCF_RESKEY_pgdata} start
+	    RC=$?
+
+	    if [[ $RC -eq 0 ]]; then
+
+		ocf_log debug "Standby instance started"
+		pgrepmgr_cib_status "STANDBY:instance standby"
+		rm -f $CLONE_LOCK
+		return $OCF_SUCCESS
+
+	    else
+
+		ocf_log err "Standby instance could not be started"
+		rm -rf $CLONE_LOCK
+		return $OCF_NOT_RUNNING
+
+	    fi
+
+	fi
+
+    fi
+    
 }
 
 pgrepmgr_cib_status() {
