Next try: implement state transition with notifications.

diff --git a/ocf/credativ/pgrepmgr_test b/ocf/credativ/pgrepmgr_test
--- a/ocf/credativ/pgrepmgr_test
+++ b/ocf/credativ/pgrepmgr_test
@@ -39,10 +39,11 @@ ATTRD_UPDATER="${HA_SBIN_DIR}/attrd_updater -q -d 0"
 PGREPMGR_STATUS_NAME="pgrepmgr-status"
 CLONE_LOCK="${OCF_RESKEY_tmpdir}/PGSQL.${OCF_RESKEY_primary_host}.${OCF_RESKEY_primary_port}.clone"
 RESOURCE="$(basename $0)"
+PGBIN="$(dirname ${OCF_RESKEY_pgctl})"
 
 ## override PATH
 ## this is a hack for repmgr, since it silently assumes to have pg_ctl in its PATH
-PATH="$PATH":"$(dirname ${OCF_RESKEY_pgctl})":"$(dirname ${OCF_RESKEY_psqlbin})"
+PATH="$PATH":"$PGBIN":"$(dirname ${OCF_RESKEY_psqlbin})"
 
 PSQLCMD="$OCF_RESKEY_psqlbin -v ON_ERROR_STOP=1 -U $OCF_RESKEY_resowner -d $OCF_RESKEY_resowner -qXtnA"
 if [[ ! -z $OCF_RESKEY_primary_port ]]; then
@@ -246,6 +247,24 @@ EOF
 }
 
 pgrepmgr_start() {
+
+    ## Perform preliminary checks
+    if ! pgrepmgr_check; then
+	ocf_log err "$RESOURCE: configuration error"
+	return $OCF_ERR_GENERIC
+    fi
+
+    ## Passing preliminary checks should guarantuee that we
+    ## can safely start the instance, but delay that until
+    ## we get the start notification from the master
+    return $OCF_SUCCESS
+
+}
+
+##
+## Internal start routine.
+##
+_pgrepmgr_start() {
 
     ocf_log info "$RESOURCE:START"
     local PGCTLRC=0
@@ -470,150 +489,139 @@ pgrepmgr_promote() {
 
 pgrepmgr_demote() {
 
+    local RC=$OCF_SUCCESS
+
+    ## Check wether this node is a primary instance
+#     pgrepmgr_get_replication_status
+#     RC=$?
+
+#     if [[ $? -eq $PGREPMGR_STATUS_IS_HOT_STANDBY ]]; then
+# 	ocf_log info "$RESOURCE demote: PostgreSQL instance already standby"
+# 	pgrepmgr_cib_status "START:refused to demote standby"
+# 	RC=$OCF_SUCCESS
+#     fi
+
+    _pgrepmgr_demote
+    return $RC
+}
+
+## Internal demote() routine
+_pgrepmgr_demote() {
+
     ## Check wether this node is a primary instance
     pgrepmgr_get_replication_status
 
-    if [[ $? -eq $PGREPMGR_STATUS_IS_HOT_STANDBY ]]; then
+    ## OK, now comes the tricky part. This is a primary instance, and we want to
+    ## demote it to a standby. This requires us to build the standby from scratch.
+    ## Since this could be a long operation, we need to take care.
+    if ! touch "$CLONE_LOCK"; then
+	ocf_log info "Could not create file \"${CLONE_LOCK}\""
+	return $OCF_ERR_GENERIC
+    fi
 
-	ocf_log info "$RESOURCE demote: PostgreSQL instance already standby"
-	pgrepmgr_cib_status "START:refused to demote standby"
-	return $OCF_SUCCESS
+    ## First, shut the server down, if not already done
+    if pgrepmgr_status ; then
+
+	ocf_log debug "Shutting down PRIMARY"
+	runasowner $OCF_RESKEY_pgctl -D $OCF_RESKEY_pgdata -m fast stop
+
+	## still alive?
+	if pgrepmgr_status ; then
+
+	    ocf_log debug "Shutting PRIMARY not succeeded, retry with immediate shutdown"
+
+	    ## oops, something is weird, maybe instance hangs somewhere,
+	    ## try to make it the hard way...
+	    runasowner $OCF_RESKEY_pgctl -D $OCF_RESKEY_pgdata -m immediate stop
+
+	    ## Wait
+	    count=0
+	    while [ $count -lt $OCF_RESKEY_stop_escalate ]
+	    do
+
+		if ! pgrepmgr_status; then
+		    # success
+		    break;
+		fi
+		count = $(expr $count + 1)
+		sleep 1
+
+	    done
+
+	fi
+
+	if pgrepmgr_status ; then
+	    ## hmm okay, something really weird is going on,
+	    ## exit immediately
+	    ocf_log info "An fatal error occured: instance is not shutting down"
+	    pgrepmgr_cib_status "ERROR:instance not shutting down"
+	    rm -f $CLONE_LOCK
+	    return $OCF_ERR_GENERIC
+	else
+	    ocf_log "Shutdown immediate succeeded"
+	fi
+
+    fi
+
+    ## If reached here, PGSQL shut be successfully shut down, proceed:
+    ## First, we need to make sure the old PGDATA isn't present anymore
+    ocf_log info "Dropping $OCF_RESKEY_pgdata"
+
+    ## if ${OCF_RESKEY_pgdata} doesn't exist yet, nothing to do here.
+    ## Otherwise we need to get rid of it, because we are forced
+    ## to resync with the primary node. This is a very destructive
+    ## task to do, so do some preliminary checks before.
+    if [[ -d "${OCF_RESKEY_pgdata}" ]]; then
+
+	## TODO: Much more checks here...
+
+	if ! rm -rf "${OCF_RESKEY_pgdata}"; then
+	    ocf_log info "Could not delete cluster directory \"${OCF_RESKEY_pgdata}\""
+	    rm -f $CLONE_LOCK
+	    return $OCF_ERR_GENERIC
+	fi
+
+    fi
+
+    ## Clone the current master
+    pgrepmgr_do_standby_clone
+
+    RC=$?
+
+    ## Handle error cases of repmgr and issue specific
+    ## error messages
+
+    if [[ $RC -ne 0 ]]; then
+
+	case $RC in
+	    1) 
+		ocf_log info "$RESOURCE demote: bad repmgr config"
+		;;
+	    2)
+		ocf_log info "$RESOURCE demote: rsync error"
+		;;
+	    3)
+		ocf_log info "$RESOURCE demote: pg_stop_backup() failed"
+		;;
+	    5)
+		ocf_log info "$RESOURCE demote: needs xlog"
+		;;
+	    *)
+		ocf_log info "$RESOURCE demote: failed to clone standby"
+		;;
+	esac
+
+	pgrepmgr_cib_status "ERROR:standby demote failed"
+
+	    ## an error has occured, cleanup
+	rm -f $CLONE_LOCK
+	return $OCF_ERR_GENERIC
 
     else
 
-	## OK, now comes the tricky part. This is a primary instance, and we want to
-	## demote it to a standby. This requires us to build the standby from scratch.
-	## Since this could be a long operation, we need to take care.
-	if ! touch "$CLONE_LOCK"; then
-	    ocf_log info "Could not create file \"${CLONE_LOCK}\""
-	    return $OCF_ERR_GENERIC
-	fi
-
-	## First, shut the server down, if not already done
-	if pgrepmgr_status ; then
-
-	    ocf_log debug "Shutting down PRIMARY"
-	    runasowner $OCF_RESKEY_pgctl -D $OCF_RESKEY_pgdata -m fast stop
-
-	    ## still alive?
-	    if pgrepmgr_status ; then
-
-		ocf_log debug "Shutting PRIMARY not succeeded, retry with immediate shutdown"
-
-		## oops, something is weird, maybe instance hangs somewhere,
-		## try to make it the hard way...
-		runasowner $OCF_RESKEY_pgctl -D $OCF_RESKEY_pgdata -m immediate stop
-
-		## Wait
-		count=0
-		while [ $count -lt $OCF_RESKEY_stop_escalate ]
-		do
-
-		    if ! pgrepmgr_status; then
-			# success
-			break;
-		    fi
-		    count = $(expr $count + 1)
-		    sleep 1
-
-		done
-
-	    fi
-
-	    if pgrepmgr_status ; then
-		## hmm okay, something really weird is going on,
-		## exit immediately
-		ocf_log info "An fatal error occured: instance is not shutting down"
-		pgrepmgr_cib_status "ERROR:instance not shutting down"
-		rm -f $CLONE_LOCK
-		return $OCF_ERR_GENERIC
-	    else
-		ocf_log "Shutdown immediate succeeded"
-	    fi
-
-	fi
-
-	## If reached here, PGSQL shut be successfully shut down, proceed:
-	## First, we need to make sure the old PGDATA isn't present anymore
-	ocf_log info "Dropping $OCF_RESKEY_pgdata"
-
-	## if ${OCF_RESKEY_pgdata} doesn't exist yet, nothing to do here.
-	## Otherwise we need to get rid of it, because we are forced
-	## to resync with the primary node. This is a very destructive
-	## task to do, so do some preliminary checks before.
-	if [[ -d "${OCF_RESKEY_pgdata}" ]]; then
-
-	    ## TODO: Much more checks here...
-
-	    if ! rm -rf "${OCF_RESKEY_pgdata}"; then
-		ocf_log info "Could not delete cluster directory \"${OCF_RESKEY_pgdata}\""
-		rm -f $CLONE_LOCK
-		return $OCF_ERR_GENERIC
-	    fi
-
-	fi
-
-	local FIN_RC=$OCF_ERR_GENERIC
-
-        ## Clone the current master
-	pgrepmgr_do_standby_clone
-
-	RC=$?
-
-	## Handle error cases of repmgr and issue specific
-	## error messages
-
-	if [[ $RC -ne 0 ]]; then
-
-	    case $RC in
-		1) 
-		    ocf_log info "$RESOURCE demote: bad repmgr config"
-		    ;;
-		2)
-		    ocf_log info "$RESOURCE demote: rsync error"
-		    ;;
-		3)
-		    ocf_log info "$RESOURCE demote: pg_stop_backup() failed"
-		    ;;
-		5)
-		    ocf_log info "$RESOURCE demote: needs xlog"
-		    ;;
-		*)
-		    ocf_log info "$RESOURCE demote: failed to clone standby"
-		    ;;
-	    esac
-
-	    pgrepmgr_cib_status "ERROR:standby demote failed"
-
-	    ## an error has occured, cleanup
-	    rm -f $CLONE_LOCK
-	    return $OCF_ERR_GENERIC
-
-	else
-
-	    ocf_log info "STANDBY CLONE ok"
-	    ocf_log debug "Starting new standby"
-
-	    ## Now start the new standby
-	    runasowner ${OCF_RESKEY_pgctl} -D ${OCF_RESKEY_pgdata} start
-	    RC=$?
-
-	    if [[ $RC -eq 0 ]]; then
-
-		ocf_log debug "Standby instance started"
-		pgrepmgr_cib_status "STANDBY:instance standby"
-		rm -f $CLONE_LOCK
-		return $OCF_SUCCESS
-
-	    else
-
-		ocf_log err "Standby instance could not be started"
-		rm -rf $CLONE_LOCK
-		return $OCF_NOT_RUNNING
-
-	    fi
-
-	fi
+	ocf_log info "STANDBY CLONE ok"
+	ocf_log debug "Starting new standby"
+	rm -f $CLONE_LOCK
 
     fi
     
@@ -628,6 +636,7 @@ pgrepmgr_notify() {
     local ACTION_TYPE=${OCF_RESKEY_CRM_meta_notify_type}
     local ACTION_OP=${OCF_RESKEY_CRM_meta_notify_operation}
     local ME=$(uname -n)
+    local RC=$OCF_SUCCESS
 
     ocf_log debug "$RESOURCE notify: received $ACTION_TYPE notification for event $ACTION_OP, master $OCF_RESKEY_CRM_meta_notify_master_uname"
 
@@ -640,9 +649,20 @@ pgrepmgr_notify() {
 		    ;;
 		demote)
 		    ocf_log debug "$RESOURCE notify: pre-demote on $ME"
+
+		    # Instance gets demoted, stop it
+		    if [[ "$OCF_RESKEY_CRM_meta_notify_demote_uname" = "$ME" ]]; then
+			pgrepmgr_stop
+			RC=$?
+		    fi
 		    ;;
 		start)
 		    ocf_log debug "$RESOURCE notify: pre-start on $ME"
+		    if [[ "$OCF_RESKEY_CRM_meta_notify_master_uname" = "$ME" ]]; then
+			## this is the master
+			_pgrepmgr_start
+			RC=$?
+		    fi
 		    ;;
 		stop)
 		    ocf_log debug "$RESOURCE notify: pre-stop on $ME"
@@ -652,20 +672,27 @@ pgrepmgr_notify() {
 	post)
 	    case $ACTION_OP in
 		promote)
-
 		    if [[ "$OCF_RESKEY_CRM_meta_notify_promote_uname" != "$ME" ]]; then
 			ocf_log debug "$RESOURCE notify: $ACTION_TYPE/$ACTION_OP resync"
 			ocf_log debug "$RESOURCE notify: master is $OCF_RESKEY_CRM_meta_notify_promote_uname"
-
-			## point to the new master
-			
 		    fi
 		    ;;
 		demote)
 		    ocf_log debug "$RESOURCE notify: post-demote on $ME"
+
+		    if [[ "$OCF_RESKEY_CRM_meta_notify_demote_uname" = "$ME" ]]; then
+			pgrepmgr_start
+			RC=$?
+		    fi
 		    ;;
 		start)
 		    ocf_log debug "$RESOURCE notify: post-start on $ME"
+
+		    if [[ "$OCF_RESKEY_meta_notify_master_uname" -ne "$ME" ]]; then
+			## this is the slave
+			_pgrepmgr_start
+			RC=$?
+		    fi
 		    ;;
 		stop)
 		    ocf_log debug "$RESOURCE notify: post-stop on $ME"
@@ -675,7 +702,7 @@ pgrepmgr_notify() {
 
     esac
 
-    return $OCF_SUCCESS;
+    return $RC;
 }
 
 pgrepmgr_do_standby_clone() {
@@ -697,8 +724,33 @@ pgrepmgr_cib_status() {
     return $OCF_SUCCESS
 }
 
-pgrepmgr_validate_all() {
+pgrepmgr_check() {
+
+    local RC=1
+    local PGDATA="${OCF_RESKEY_pgdata}"
+
+    ## Check if PGDATA was specified and exists
+    if [[ ! -d "$PGDATA" ]]; then
+	ocf_log err "$RESOURCE: \"$PGDATA\" does not exist"
+	return $OCF_ERR_GENERIC
+    fi
+
+    ## Okay, PGDATA exists, but does it actually contain
+    ## a valid PostgreSQL cluster directory?
+    "$PGBIN"/pg_controldata "$OCF_RESKEY_pgdata" 1>/dev/null
+    RC=$?
+
+    if [[ $RC -ne 0 ]]; then
+	ocf_log err "$RESOURCE: \"$PGDATA\" does not contain a valid PostgreSQL cluster"
+	return $OCF_ERR_GENERIC
+    fi
+
     return $OCF_SUCCESS
+}
+
+pgrepmgr_validate_all() {
+    pgrepmgr_check
+    return $?
 }
 
 #
